### ISSUE TITLE
authentication  error

### ISSUE THREAD

**Issue by rose9805** [microsoft/Partner-Center-Java-Samples#20]
The sample sdk source execution result is as follows:
-------------------------------------------------- ------------------------------
Partner Center Java SDK samples
-------------------------------------------------- ------------------------------

1: Customer samples
2: Agreements
3: Offer samples
4: Product samples
5: Products for customers samples
6: Order samples
7: Subscription samples
8: Rated Usage samples
9: Service request samples
10: Invoice samples
11: Partner Profile samples
12: Customer User samples
13: Customer Subscribed Skus samples
14: Customer Directory Role samples
15: Auditing samples
16: Rate Card samples
17: Indirect model samples
18: Service Incident samples
19: Utilization samples
20: Partner Analytics samples
21: Customer service costs samples
22: Address validation samples
23: Devices
24: Cart Scenarios
25: Entitlements

Enter the scenario number to run (press Q to exit to previous screen): 20

-------------------------------------------------- ------------------------------
Partner Analytics samples
-------------------------------------------------- ------------------------------

1: Get partner licenses deployment analytics
2: Get partner licenses usage analytics
3: Get customer licenses deployment analytics
4: Get customer licenses usage analytics

Enter the scenario number to run (press Q to exit to previous screen): 1

-------------------------------------------------- ------------------------------
Get partner licenses deployment analytics
-------------------------------------------------- ------------------------------

Authenticating user ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: Server returned HTTP response code: 400 for URL: https://login.windows.net/common/oauth2/devicecode?resource=https%3A% 2F% 2Fapi.partnercenter.microsoft.com & client_id = 6741dc05-403f-4e86-a70e-abb7497c3ebc, Error details: {"error": "invalid_request", "error_description": "AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials. \ r \ nTrace ID: 49a48aea-ca5e-4566-82d8-ade3fa047401 \ r \ nCorrelation ID: dd29a5f6-d045-4374-a526-a3f5e0dc38fb \ r \ n \ Time \ amp: 2019-09-06 00:42: 54Z "," error_codes ": [50059]," timestamp ":" 2019-09-06 00: 42: 54Z "," trace_id ":" 49a48aea-ca5e-4566-82d8-ade3fa047401 "," correlation_id ":" dd29a5f6 -d045-4374-a526-a3f5e0dc38fb "}
[Error] java.lang.NullPointerException: authentication result was null

I received an error message from the partner center.

What should I do?

**Comment by rose9805** [comment]
The error details are as follows.
When does the error occur?
How can I solve it?
What should I do? …..
Is this issue also I should post on github?
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HMAXUQGTN to authenticate.
java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 020cfc02-9097-4e4e-ace2-5ca71fd79f00\r\nCorrelation ID: cdf745ca-447f-4ad6-8c35-a5af27b5e2d5\r\nTimestamp: 2019-09-10 10:15:12Z","error":"invalid_client","error_uri":"https:\/\/login.windows.net\/error?code=7000218"}
           at java.util.concurrent.FutureTask.report(FutureTask.java:122)
           at java.util.concurrent.FutureTask.get(FutureTask.java:192)
           at com.microsoft.store.partnercenter.samples.AadUserLoginHandler.SendTokenRequest(AadUserLoginHandler.java:111)
           at com.microsoft.store.partnercenter.samples.AadUserLoginHandler.authenticate(AadUserLoginHandler.java:68)
           at com.microsoft.store.partnercenter.samples.context.ScenarioContext.getUserPartnerOperations(ScenarioContext.java:102)
           at com.microsoft.store.partnercenter.samples.profiles.GetBillingProfile.runScenario(GetBillingProfile.java:36)
           at com.microsoft.store.partnercenter.samples.BasePartnerScenario.run(BasePartnerScenario.java:136)
           at com.microsoft.store.partnercenter.samples.scenarioexecution.AggregateScenarioExecutionStrategy.isScenarioComplete(AggregateScenarioExecutionStrategy.java:50)
           at com.microsoft.store.partnercenter.samples.BasePartnerScenario.run(BasePartnerScenario.java:145)
           at com.microsoft.store.partnercenter.samples.scenarioexecution.AggregateScenarioExecutionStrategy.isScenarioComplete(AggregateScenarioExecutionStrategy.java:50)
           at com.microsoft.store.partnercenter.samples.BasePartnerScenario.run(BasePartnerScenario.java:145)
           at com.microsoft.store.partnercenter.samples.Program.main(Program.java:189)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 020cfc02-9097-4e4e-ace2-5ca71fd79f00\r\nCorrelation ID: cdf745ca-447f-4ad6-8c35-a5af27b5e2d5\r\nTimestamp: 2019-09-10 10:15:12Z","error":"invalid_client","error_uri":"https:\/\/login.windows.net\/error?code=7000218"}
           at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)
           at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
           at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
           at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
           at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
           at java.lang.Thread.run(Thread.java:748)
