### ISSUE TITLE
"The Azure Key Vault url is malformed" exception

### ISSUE THREAD

**Issue by abitgcp** [microsoft/Partner-Center-Java-Samples#41]
Steps to reproduce:
Clone Git repo in local eclipse. Update keyvalue_base_url to a valid value in web.xml.
Add Tomcat server and run the partnerconsent app.

## Expected behavior
No exception

> Share the expected output

## Actual behavior

```
SEVERE: Exception starting filter [AuthenticationFilter]
java.lang.IllegalArgumentException: The Azure Key Vault url is malformed.
    at com.azure.security.keyvault.secrets.SecretClientBuilder.vaultUrl(SecretClientBuilder.java:177)
    at com.microsoft.store.samples.partnerconsent.security.KeyVaultProvider.getKeyVaultClient(KeyVaultProvider.java:68)
    at com.microsoft.store.samples.partnerconsent.security.KeyVaultProvider.<init>(KeyVaultProvider.java:33)
    at com.microsoft.store.samples.partnerconsent.security.AuthenticationFilter.init(AuthenticationFilter.java:236)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:272)
    ...
```
    
  I have used a valid value of format - https://some-name.vault.azure.net/ as keyvault_base_url but still facing the exception.

**Comment by abitgcp** [comment]
@msftgits and other repository owners/contributors - I have identified the bug

the arrowed statement (in the image) should come above the below statement because getKeyVaultClient method is using the variable vaultBaseUrl.
client = getKeyVaultClient();

<img width="1177" alt="Screenshot 2023-02-21 at 8 42 17 PM" src="https://user-images.githubusercontent.com/125907066/220384732-716e5084-5238-4277-ab15-1d21b2375c75.png">

Please make this change in the code.
