### ISSUE TITLE
class java.util.Collections$SingletonList cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by abitgcp** [microsoft/Partner-Center-Java-Samples#43]
I am getting this exception on running the partnerconsent project. 
class java.util.Collections$SingletonList cannot be cast to class java.lang.String (java.util.Collections$SingletonList and java.lang.String are in module java.base of loader 'bootstrap')

```
java.lang.ClassCastException: class java.util.Collections$SingletonList cannot be cast to class java.lang.String (java.util.Collections$SingletonList and java.lang.String are in module java.base of loader 'bootstrap')
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:103)
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:160)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

<img width="1372" alt="Screenshot 2023-02-22 at 5 40 15 PM" src="https://user-images.githubusercontent.com/125907066/220616198-c93c859a-a563-473b-8067-45e17948f805.png">

Please look into this.

**Comment by abitgcp** [comment]
@idwilliams, @msftgits, @microsoftopensource, @Luyunmt and other contributors/readers
I would appreciate your help if you could look into this. Thanks!
